
provers = [ "zip", "zip-avatar" ]
timeout = 10
memory = 2000

default_expect = "unsat"
problems = ".*\\.zf"

[test]

dir = ["."]

[zip]

binary = "zipperposition"
cmd = "zipperposition $file --timeout $timeout --debug 0 --mem-limit $memory"
unsat = "SZS status (Theorem|Unsatisfiable)"
sat = "SZS status (CounterSatisfiable|Satisfiable)"

[zip-avatar]

binary = "zipperposition"
cmd = "zipperposition $file --timeout $timeout --debug 0 --mem-limit $memory --avatar"
unsat = "SZS status (Theorem|Unsatisfiable)"
sat = "SZS status (CounterSatisfiable|Satisfiable)"

